version: "3.8"
services:
  app:
    pull_policy: build
    build:
      context: ./
    restart: unless-stopped
    volumes:
      - sqlite-db:/app/db/
    environment:
      - TOKEN=${TOKEN}
      - APP_ID=${APP_ID}
      - SERVER_ID=${SERVER_ID}
      - SAD_EMOTE=${SAD_EMOTE}
      - HAPPY_EMOTE=${HAPPY_EMOTE}
      - LAUGH_EMOTE=${LAUGH_EMOTE}
      - PRAY_EMOTE=${PRAY_EMOTE}
      - TEXT_CHANNEL=${TEXT_CHANNEL}
      - VOICE_CHANNEL=${VOICE_CHANNEL}

volumes:
  sqlite-db:
